### ISSUE TITLE
Grafana error  Template variable could not be initialized: Network Error:  bad Gateway(502)

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [AzureIoTGBB/iot-edge-offline-dashboarding#13]
When we pull up the Grafana GUI and try to access dashboard we receive: 
Templating
Template variables could not be initialized: Network Error: Bad Gateway(502)

Grafana log (from the IOT Edge VM):  

t=2020-08-04T19:14:35+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/flux/api/v2/query remote_addr=47.187.118.166 referer="http://13.90.25.91:3000/d/xIrX9siGz/production-at-a-glance?orgId=1" error="http: proxy error: unsupported protocol scheme \"\""
t=2020-08-04T19:14:35+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/flux/api/v2/query status=502 remote_addr=47.187.118.166 time_ms=2 size=0 referer=http://13.90.25.91:3000/d/xIrX9siGz/production-at-a-glance?orgId=1

**FIX: Yup I need to RTM** 

[!NOTE] There is currently a bug: For some reason, the data source details are deployed correctly, however not shown as 'enabled'. This will cause the dashboard to display an error and not show any data.

When logged in, click the gear icon on the left-hand panel and select data sources -> "myinfluxdb" to navigate into the settings.

**Comment by MikeWilcoxMicrosoft** [comment]
Docs clearly state and fix the issue.. 
[!NOTE] There is currently a bug: For some reason, the data source details are deployed correctly, however not shown as 'enabled'. This will cause the dashboard to display an error and not show any data.

When logged in, click the gear icon on the left-hand panel and select data sources -> "myinfluxdb" to navigate into the settings.

**Comment by ghost** [comment]
@MikeWilcoxMicrosoft RTM = restart the machine?
